### ISSUE TITLE
ERROR when deploy gcf for a param change --stage-bucket

### ISSUE THREAD

**Issue by pepetox** [carlosgalveias/gcccli#1]
When try to deploy:

ERROR: (gcloud.alpha.functions.deploy) unrecognized arguments:
  --bucket (did you mean '--stage-bucket'?)

BTW: Thanks for this cli, is amazing!

**Comment by carlosgalveias** [comment]
Glad you liked it. Thanks for the report, ill fix it today

Em 02/03/2017 15:24, "Pepetox" <notifications@github.com> escreveu:

**Comment by carlosgalveias** [comment]
@Pepetox,

Fixed it , please update gccli to version 0.1.5 and do gccli reset, answer
Yes. It will not delete any models, etc.

It also fixed to support a change in the req.params in gcf.

Regards

Carlos Galveias

2017-03-03 12:49 GMT+00:00 Carlos Galveias <carlos.galveias@gmail.com>:
